version: "3.8"

services:
  php:
    build: .
    container_name: prueba_tecnica_php
    volumes:
      - .:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: prueba_tecnica_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: prueba_tecnica_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: technologiesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"
