version: "3.8"

services:
  php:
    build: .
    container_name: prueba_tecnica_php
    volumes:
      - .:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql
    command: >
      sh -c "
      echo 'Iniciando configuración inicial...' &&

      echo 'Esperando a que MySQL esté listo...' &&
      until nc -z -v -w30 mysql 3306; do
        echo 'MySQL aún no está listo...'
        sleep 5
      done &&
      echo 'MySQL está listo!' &&

      if [ ! -d 'vendor' ]; then
        echo 'Instalando dependencias de Composer...' &&
        composer install --no-interaction --optimize-autoloader &&
        composer require symfony/cache &&
        composer require --dev phpunit/phpunit
      else
        echo 'Dependencias de Composer ya instaladas, saltando instalación.'
      fi &&

      echo 'Actualizando esquema de base de datos con Doctrine...' &&
      vendor/bin/doctrine orm:schema-tool:update --force --complete &&

      echo 'Configuración completa. Iniciando PHP-FPM...' &&
      php-fpm"

  nginx:
    image: nginx:latest
    container_name: prueba_tecnica_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: prueba_tecnica_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: technologiesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"
    